"""Subclass of OccupationFinder, which is generated by wxFormBuilder."""

import wx

import AppsSDS.sds as sds


# Implementing OccupationFinder
class SDSHollandOccupationFinder(sds.OccupationFinder):

	def __init__(self, parent):
		sds.OccupationFinder.__init__(self, parent)

	# Handlers for OccupationFinder events.
	def OccupationF_tombol_okOnButtonClick(self, event):
		# TODO: Implement OccupationF_tombol_okOnButtonClick
		pass

	def btn_occupationfinder(self, event):
		# TODO: Implement btn_occupationfinder
		pass

