"""Subclass of Page2, which is generated by wxFormBuilder."""

import wx
import sds


# Implementing Page2
class SDSHollandPage2(sds.Page2):

	def __init__(self, parent):
		sds.Page2.__init__(self, parent)

