"""Subclass of Page2hide, which is generated by wxFormBuilder."""

import wx

import sds


# Implementing Page2hide
class SDSHollandPage2hide(sds.Page2hide):

	def __init__(self, parent):
		sds.Page2hide.__init__(self, parent)

	# Handlers for Page2hide events.
	def m_openlistbox1(self, event):
		# TODO: Implement m_openlistbox1
		pass

