"""Subclass of WindowUtama, which is generated by wxFormBuilder."""

import wx
import sds

# Implementing WindowUtama
class SDSHollandWindowUtama( sds.WindowUtama ):
	def __init__( self, parent ):
		sds.WindowUtama.__init__( self, parent )


	# Handlers for WindowUtama events.
	def btn_Close( self, event ):
		# TODO: Implement btn_Close
		print ("Tutup Aplikasi")
		self.Close(True)
		pass

	def btn_gotopage2( self, event ):
		# TODO: Implement btn_gotopage2
		from SDSHollandPage3 import SDSHollandPage3
		#SDSHollandPage2(self)
		self.SetScrollbar(1,1,400,300)
		SDSHollandPage3.m_scrollBar1OnScroll(self,event)
		self.m_panel10.Hide()
		self.m_panel2.Show()
		#SDSHollandPage3(self)
		self.Layout()

		pass


