#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.0a1 on Sat Nov  3 12:58:29 2018
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MPython.RUtama import RUtama


class MyApp(wx.App):
    def OnInit(self):
        self.Frame = RUtama(None, wx.ID_ANY, "")
        self.SetTopWindow(self.Frame)
        self.Frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
