# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.1 on Fri Nov  2 21:25:46 2018
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import a
# end wxGlade


class RUtama(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RUtama.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        import b
        self.window_1 = ahhjh(self.panel_1, wx.ID_ANY)
        import c
        
        # Menu Bar
        self.Frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.Frame_menubar.koneksi = wxglade_tmp_menu.Append(12, "Koneksi", "Menghubungkan koneksi")
        self.Bind(wx.EVT_MENU, self.btn_buka_koneksi, id=12)
        self.Frame_menubar.Append(wxglade_tmp_menu, "Berkas")
        wxglade_tmp_menu = wx.Menu()
        self.Frame_menubar.info = wxglade_tmp_menu.Append(11, "Info", "Informasi Binakarir")
        self.Bind(wx.EVT_MENU, self.buka_info, id=11)
        self.Frame_menubar.Append(wxglade_tmp_menu, "Tentang")
        self.SetMenuBar(self.Frame_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RUtama.__set_properties
        self.SetTitle("Binakarir")
        self.window_1.SetDasdcv(bb)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RUtama.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.window_1, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def btn_buka_koneksi(self, event):  # wxGlade: RUtama.<event_handler>
        print("Event handler 'btn_buka_koneksi' not implemented!")
        event.Skip()
    def buka_info(self, event):  # wxGlade: RUtama.<event_handler>
        print("Event handler 'buka_info' not implemented!")
        event.Skip()
# end of class RUtama
